title: "Archilogic Documentation"

host: localhost

highlighter: rouge

favicon: https://about.archilogic.com/wp-content/uploads/favicon-96x96.png

# list of additional links on the right of the top menu
headerLinks:
  - linkName: About
    url: http://about.archilogic.com

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']
